@startuml

package base {
	!include ./include/base/package.iuml
}

package brewery {
	!include ./include/brewery/package.iuml
}

package raccordable {
	!include ./include/raccordable/package.iuml
}

package actionnable {
	!include ./include/actionnable/package.iuml
}

package collectable {
	!include ./include/collectable/package.iuml
}

package interface {
	!include ./include/interface/package.iuml
}

@enduml

