@startuml
!include ./include/objetBase.iuml
!include ./include/metadonnee.iuml
!include ./include/note.iuml
!include ./include/utilisateur.iuml
!include ./include/assoc/note_objetBase.iuml
!include ./include/assoc/note_utilisateur.iuml
!include ./include/assoc/objetBase_metadonnee.iuml
@enduml