@startuml
!include ./include/baseObject.iuml
!include ./include/brewery.iuml
!include ./include/user.iuml
!include ./include/brewer.iuml
!include ./include/equipment.iuml
!include ./include/waterSupply.iuml
!include ./include/powerSupply.iuml
!include ./include/powerType.iuml
!include ./include/addon.iuml
!include ./include/pump.iuml
!include ./include/brewpot.iuml
!include ./include/manifold.iuml
!include ./include/te.iuml
!include ./include/component.iuml
!include ./include/cooler.iuml
!include ./include/hardware.iuml
!include ./include/insulator.iuml
!include ./include/filter.iuml
!include ./include/coil.iuml
!include ./include/shower.iuml
!include ./include/valve.iuml
!include ./include/heater.iuml
!include ./include/mixer.iuml
!include ./include/fermentationChamber.iuml

!include ./include/assoc/user_brewer.iuml
!include ./include/assoc/baseObject_hardware.iuml
!include ./include/assoc/brewery_brewer.iuml
!include ./include/assoc/brewery_equipment.iuml
!include ./include/assoc/equipment_waterSupply.iuml
!include ./include/assoc/equipment_powerSupply.iuml
!include ./include/assoc/equipment_environment.iuml
!include ./include/assoc/equipment_component.iuml
!include ./include/assoc/component_pump.iuml
!include ./include/assoc/component_brewpot.iuml
!include ./include/assoc/component_manifold.iuml
!include ./include/assoc/component_fermentationChamber.iuml
!include ./include/assoc/addon_te.iuml
!include ./include/assoc/component_addon.iuml

!include ./include/assoc/addon_heater.iuml
!include ./include/assoc/addon_cooler.iuml
!include ./include/assoc/addon_coil.iuml
!include ./include/assoc/addon_filter.iuml
!include ./include/assoc/addon_shower.iuml
!include ./include/assoc/addon_valve.iuml
!include ./include/assoc/addon_insulator.iuml

!include ./include/assoc/hardware_addon.iuml
!include ./include/assoc/hardware_component.iuml
@enduml