@startuml
!include ./include/baseObject.iuml
!include ./include/brewery.iuml
!include ./include/user.iuml
!include ./include/brewer.iuml
!include ./include/equipment.iuml
!include ./include/waterSupply.iuml
!include ./include/powerSupply.iuml
!include ./include/powerType.iuml
!include ./include/component.iuml
!include ./include/pump.iuml
!include ./include/brewpot.iuml
!include ./include/manifold.iuml
!include ./include/te.iuml
!include ./include/resource.iuml
!include ./include/cooler.iuml

!include ./include/insulator.iuml
!include ./include/filter.iuml
!include ./include/coil.iuml
!include ./include/shower.iuml
!include ./include/valve.iuml
!include ./include/heater.iuml
!include ./include/mixer.iuml

!include ./include/assoc/user_brewer.iuml
!include ./include/assoc/brewery_brewer.iuml
!include ./include/assoc/brewery_equipment.iuml
!include ./include/assoc/brewery_waterSupply.iuml
!include ./include/assoc/brewery_powerSupply.iuml
!include ./include/assoc/brewery_environment.iuml
!include ./include/assoc/equipment_resource.iuml
!include ./include/assoc/resource_baseObject.iuml
!include ./include/assoc/resource_pump.iuml
!include ./include/assoc/resource_brewpot.iuml
!include ./include/assoc/resource_manifold.iuml
!include ./include/assoc/resource_cooler.iuml
!include ./include/assoc/resource_te.iuml
!include ./include/assoc/resource_component.iuml

!include ./include/assoc/component_heater.iuml
!include ./include/assoc/component_coil.iuml
!include ./include/assoc/component_filter.iuml
!include ./include/assoc/component_shower.iuml
!include ./include/assoc/component_valve.iuml

@enduml