@startuml
!include ./include/equipement.iuml
!include ./include/composant.iuml
!include ./include/pompe.iuml
!include ./include/cuve.iuml
!include ./include/nourrice.iuml
!include ./include/te.iuml
!include ./include/ressource.iuml
!include ./include/refroidisseurPlaques.iuml
!include ./include/assoc/brasserie_equipement.iuml
!include ./include/assoc/equipement_ressource.iuml
!include ./include/assoc/ressource_objetBase.iuml
!include ./include/assoc/ressource_pompe.iuml
!include ./include/assoc/ressource_cuve.iuml
!include ./include/assoc/ressource_nourrice.iuml
!include ./include/assoc/ressource_refroidisseurPlaques.iuml
!include ./include/assoc/ressource_te.iuml
!include ./include/assoc/ressource_composant.iuml
@enduml