@startuml
!include ./include/raccordable.iuml
!include ./include/pump.iuml
!include ./include/te.iuml
!include ./include/manifold.iuml
!include ./include/evacuation.iuml
!include ./include/tuyau.iuml
!include ./include/raccord.iuml
!include ./include/shower.iuml
!include ./include/filter.iuml
!include ./include/coil.iuml
!include ./include/valve.iuml
!include ./include/branchement.iuml
!include ./include/assoc/raccordable_alimentationEau.iuml
!include ./include/assoc/raccordable_douchette.iuml
!include ./include/assoc/raccordable_filtre.iuml
!include ./include/assoc/raccordable_manifold.iuml
!include ./include/assoc/raccordable_pompe.iuml
!include ./include/assoc/raccordable_raccord.iuml
!include ./include/assoc/raccordable_refroidisseurPlaques.iuml
!include ./include/assoc/raccordable_serpentin.iuml
!include ./include/assoc/raccordable_te.iuml
!include ./include/assoc/raccordable_vanne.iuml
!include ./include/assoc/branchement_raccord.iuml
!include ./include/assoc/branchement_tuyau.iuml
@enduml