@startuml
!define GIT_URL https://raw.githubusercontent.com/beerfactory/brewbox-uml/master

!includeurl GIT_URL/actionnable.iuml
!includeurl GIT_URL/actionneur.iuml
!includeurl GIT_URL/alimentationEau.iuml
!includeurl GIT_URL/alimentationElectrique.iuml
!includeurl GIT_URL/branchement.iuml
!includeurl GIT_URL/brasserie.iuml
!includeurl GIT_URL/brasseur.iuml
!includeurl GIT_URL/captage.iuml
!includeurl GIT_URL/capteur.iuml
!includeurl GIT_URL/carteInterface.iuml
!includeurl GIT_URL/chambreFermentation.iuml
!includeurl GIT_URL/chauffage.iuml
!includeurl GIT_URL/common.iuml
!includeurl GIT_URL/composant.iuml
!includeurl GIT_URL/controleur.iuml
!includeurl GIT_URL/coude.iuml
!includeurl GIT_URL/cuve.iuml
!includeurl GIT_URL/douchette.iuml
!includeurl GIT_URL/echantillon.iuml
!includeurl GIT_URL/echantillonneur.iuml
!includeurl GIT_URL/emplacementCapteur.iuml
!includeurl GIT_URL/environnement.iuml
!includeurl GIT_URL/equipement.iuml
!includeurl GIT_URL/evacuation.iuml
!includeurl GIT_URL/fauxFond.iuml
!includeurl GIT_URL/filtre.iuml
!includeurl GIT_URL/fluide.iuml
!includeurl GIT_URL/isolant.iuml
!includeurl GIT_URL/melangeur.iuml
!includeurl GIT_URL/metadonnee.iuml
!includeurl GIT_URL/note.iuml
!includeurl GIT_URL/nourrice.iuml
!includeurl GIT_URL/objetBase.iuml
!includeurl GIT_URL/peripherique.iuml
!includeurl GIT_URL/pompe.iuml
!includeurl GIT_URL/raccord.iuml
!includeurl GIT_URL/raccordable.iuml
!includeurl GIT_URL/refroidisseurPlaques.iuml
!includeurl GIT_URL/serie.iuml
!includeurl GIT_URL/serpentin.iuml
!includeurl GIT_URL/te.iuml
!includeurl GIT_URL/tresse.iuml
!includeurl GIT_URL/tuyau.iuml
!includeurl GIT_URL/typeAlimentation.iuml
!includeurl GIT_URL/utilisateur.iuml
!includeurl GIT_URL/vanne.iuml
!includeurl GIT_URL/assoc/actionneur_controleur.iuml
!includeurl GIT_URL/assoc/branchement_raccord.iuml
!includeurl GIT_URL/assoc/brasserie_alimentationElectrique.iuml
!includeurl GIT_URL/assoc/brasserie_brasseur.iuml
!includeurl GIT_URL/assoc/brasserie_environnement.iuml
!includeurl GIT_URL/assoc/brasserie_equipement.iuml
!includeurl GIT_URL/assoc/captage_alimentationElectrique.iuml
!includeurl GIT_URL/assoc/captage_alimentationEau.iuml
!includeurl GIT_URL/assoc/captage_cuve.iuml
!includeurl GIT_URL/assoc/captage_emplacementCapteur.iuml
!includeurl GIT_URL/assoc/captage_environnement.iuml
!includeurl GIT_URL/assoc/captage_fluide.iuml
!includeurl GIT_URL/assoc/captage_pompe.iuml
!includeurl GIT_URL/assoc/capteur_echantillonneur.iuml
!includeurl GIT_URL/assoc/carteInterface_peripherique.iuml
!includeurl GIT_URL/assoc/controleur_peripherique.iuml
!includeurl GIT_URL/assoc/echantillonneur_serie.iuml
!includeurl GIT_URL/assoc/emplacementCapteur_capteur.iuml
!includeurl GIT_URL/assoc/brasserie_alimentationEau.iuml
!includeurl GIT_URL/assoc/equipement_chambreFermentation.iuml
!includeurl GIT_URL/assoc/equipement_composant.iuml
!includeurl GIT_URL/assoc/equipement_cuve.iuml
!includeurl GIT_URL/assoc/equipement_evacuation.iuml
!includeurl GIT_URL/assoc/equipement_raccord.iuml
!includeurl GIT_URL/assoc/equipement_nourrice.iuml
!includeurl GIT_URL/assoc/equipement_pompe.iuml
!includeurl GIT_URL/assoc/equipement_refroidisseurPlaques.iuml
!includeurl GIT_URL/assoc/note_objetBase.iuml
!includeurl GIT_URL/assoc/note_utilisateur.iuml
!includeurl GIT_URL/assoc/objetBase_metadonnee.iuml
!includeurl GIT_URL/assoc/peripherique_echantillonneur.iuml
!includeurl GIT_URL/assoc/raccordable_raccord.iuml
!includeurl GIT_URL/assoc/raccordable_nourrice.iuml
!includeurl GIT_URL/assoc/raccordable_pompe.iuml
!includeurl GIT_URL/assoc/raccordable_refroidisseurPlaques.iuml
!includeurl GIT_URL/assoc/serie_echantillon.iuml
!includeurl GIT_URL/assoc/utilisateur_brasseur.iuml
@enduml

