class Coude <<Raccordable>> {
    diametreExterne : DecimalCourt
    diametreInterne : DecimalCourt
    matiere : Chaine
    angleCoude : DecimalCourt    
}

Raccordable <|-- Coude
Composant <|-- Coude
