class Cuve {
    volumeMax : EntierCourt
    volumeUtile : EntierCourt
    hauteur : EntierCourt
    diametre : EntierCourt
    profondeur : EntierCourt
    masseVide : EntierCourt
    matiere : Chaine
}

Ressource <|-- Cuve
