class EntreeFluide <<Captage>> {
	interneEquipement : booleen
}
class SortieFluide  <<Captage>> {
	interneEquipement : booleen
}

enum TypeFluide {
    EAU
    MOUT
    BIERE
}

EntreeFluide -- "1" TypeFluide
SortieFluide -- "1" TypeFluide
Captage <|-- EntreeFluide
Captage <|-- SortieFluide
