class Raccord {
    diametreRaccord : DecimalCourt
    typeRaccord : Chaine
}

enum GenreRaccord {
    MALE
    FEMELLE
}

enum SensFluide {
	ENTREE
	SORTIE
}

ObjetBase <|-- Raccord
Raccord -- "1" GenreRaccord
Raccord -- "1" SensFluide
