abstract class Capteur {
}

class Thermometre {
    type : TypeThermometre
}

enum TypeThermometre {
    THERMOCOUPLE
    THERMISTANCE
    PT100
}

class Debitmetre {
    
}

class Niveau {
    
}

class PHmetre {
    
}

ObjetBase <|-- Capteur
Capteur <|-- Thermometre
Capteur <|-- Debitmetre
Capteur <|-- Niveau
Capteur <|-- PHmetre
