abstract class Echantillonneur {
	intervalle : EntierCourt
}

Echantillonneur <|-- EchantillonneurCAN
Echantillonneur <|-- EchantillonneurI2C
Echantillonneur <|-- Echantillonneur1W
Echantillonneur <|-- EchantillonneurGPIO
