class Fitting {
    diametreRaccord : DecimalCourt
    typeRaccord : Chaine
    genre : GenreRaccord
    sens : SensFluide
}

enum GenreRaccord {
    MALE
    FEMELLE
}

enum SensFluide {
	ENTREE
	SORTIE
}

