package raccordable {

	class Fitting {
	    diameter : Float
	    type : String
	    gender : FittingGender
	    direction : LiquidDirection
	}

	enum FittingGender {
	    MALE
	    FEMALE
	}

	enum LiquidDirection {
		INPUT
		OUTPUT
	}
}
