package collectable {
	abstract class Sensor {
	}

	class Thermometer {
	}

	enum ThermometerType {
	    THERMOCOUPLE
	    THERMISTANCE
	    PT100
	}

	class FlowMeter {
	    
	}

	class Level {
	    
	}

	class PHMeter {
	    
	}
}

Sensor <|-- Thermometer
Sensor <|-- FlowMeter
Sensor <|-- Level
Sensor <|-- PHMeter

Thermometer -- "1" ThermometerType : type
