class Equipment {
    + installDate : Timestamp
}

enum EquipmentState {
    PLANNED
    INSTALLED
    ACTIVE
    INACTIVE
    RETIRED
}

BaseObject <|-- Equipment
Equipment -- "1" EquipmentState : state