!include ./brewery.iuml
!include ./brewer.iuml
!include ./equipment.iuml
!include ./waterSupply.iuml
!include ./powerSupply.iuml
!include ./powerType.iuml
!include ./brewpotAddon.iuml
!include ./pump.iuml
!include ./brewpot.iuml
!include ./manifold.iuml
!include ./plumbingElement.iuml
!include ./environment.iuml
!include ./component.iuml
!include ./cooler.iuml
!include ./hardware.iuml
!include ./insulator.iuml
!include ./filter.iuml
!include ./coil.iuml
!include ./shower.iuml
!include ./valve.iuml
!include ./heater.iuml
!include ./mixer.iuml
!include ./heatExchanger.iuml
!include ./heatingElement.iuml
!include ./hose.iuml
!include ./fitting.iuml

!include ./assoc/user_brewer.iuml
!include ./assoc/baseObject_hardware.iuml
!include ./assoc/brewery_brewer.iuml
!include ./assoc/brewery_equipment.iuml
!include ./assoc/equipment_waterSupply.iuml
!include ./assoc/equipment_powerSupply.iuml
!include ./assoc/equipment_environment.iuml
!include ./assoc/equipment_component.iuml
!include ./assoc/equipment_evacuation.iuml
!include ./assoc/component_pump.iuml
!include ./assoc/component_brewpot.iuml
!include ./assoc/component_manifold.iuml
!include ./assoc/component_plumbingElement.iuml
!include ./assoc/component_heatExchanger.iuml
!include ./assoc/hardware_heater.iuml
!include ./assoc/hardware_cooler.iuml
!include ./assoc/hardware_hose.iuml
!include ./assoc/brewpotAddon_coil.iuml
!include ./assoc/component_filter.iuml
!include ./assoc/brewpotAddon_shower.iuml
!include ./assoc/component_valve.iuml
!include ./assoc/brewpotAddon_insulator.iuml
!include ./assoc/brewpotAddon_mixer.iuml
!include ./assoc/brewpotAddon_heatingElement.iuml
!include ./assoc/hardware_component.iuml
!include ./assoc/hardware_fitting.iuml
!include ./assoc/hardware_brewpotAddon.iuml
!include ./assoc/brewpot_brewpotAddon.iuml
!include ./assoc/environment_cooler_heater.iuml
