!include ./actionnable.iuml
!include ./actuator.iuml
!include ./resistor.iuml
!include ./controler.iuml

!include ./assoc/actionnable_pump.iuml
!include ./assoc/actionnable_mixer.iuml
!include ./assoc/actionnable_electrovalve.iuml
!include ./assoc/actuator_controler.iuml
!include ./assoc/actionnable_heatingElement.iuml
!include ./assoc/actionnable_actuator.iuml
!include ./assoc/actuator_resistor.iuml
